services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: articles-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_ENCRYPT=0
    ports:
      - "14330:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: